### ISSUE TITLE
Is PSHealthz Prometheus compatible?

### ISSUE THREAD

**Issue by Outek** [devblackops/pshealthz#1]
Im curious about your Healthz module. Do you have in use with Prometheus or how do you consume the data from the endpoints?

**Comment by devblackops** [comment]
@Outek I didn't design it with Prometheus specifically in mind. 

My use case was creating simple smoke test modules with [OVF](https://github.com/PowerShell/Operation-Validation-Framework) and [Pester] (https://github.com/pester/Pester). These smoke tests could then be invoked via a ChatOps framework.

How would you see it being used with Prometheus?

**Comment by Outek** [comment]
Well, my idea is to run a Service (something similar to PSHealthz) which is executing Pester/OVF Tests to validate the operational state of a server. In our company, a lot of Things going to get monitored by Prometheus, so i'm actually looking for something for Windows server / containers.

**Comment by devblackops** [comment]
Gotcha. I suppose PSHealthZ could be modified to create a `/metrics` endpoint. I haven't messed with Prometheus, only read about it. Would the thought be that hitting that endpoint would automatically run the Pester/OVF tests or would the service run them at a set schedule and then publish them to the endpoint so prom could scrap the data quickly?

**Comment by Outek** [comment]
I'm no Prometheus expert either. What would you think is the lightweight way to gather metrics with Powershell, since the overhead of starting multiple Powershell processes is exhausting for small servers?

As far as I know, Prometheus require a quick(whatever quick means) response time when it is scrapping data, maybe I can find the source of this information. 
If this is true and the OVF Test-Set can be pretty detailed, I would probably go for a service.
